ferret:
  ignore:
    - ".*"
    - "*.json"
    - LICENSE
    - "*.lock"
    - "*.log"
    - "*.md"
    - .docs-site/
    - src/@types
    - test/fixtures
    - dist
    - build
    - meta
    - test/mocha.opts
    - "*.yml"

depcheck:
  config:
    ignore_deps:
      - "@types/**"
      - "ferret-**"
    ignore_dirs:
      - src
      - .docs

retire:
  config:
    node: true
    package: true
    js: false
    ignore:
      - .docs

synt:
  ignore: lib

comment:
  ignore: lib

eclint:
  ignore: lib

language:
  ignore: lib

stat:
  ignore:
    - src/@types/**

license:
  config:
    allowed:
      - MIT
      - ISC
      - MPL-2.0
      - LGPL
      - GPL
      - BSD
      - Apache
      - Unlicense
      - Artistic
      - WTFPL
      - Public Domain
      - CC-BY-3.0
      - CC-BY-4.0
      - CC0-1.0
    ignored:
      - classifier   # MIT https://github.com/harthur/classifier/blob/master/LICENSE
      - event-stream # MIT https://github.com/dominictarr/event-stream/blob/master/LICENCE
      - goo.gl       # See: https://github.com/kaimallea/node-googl/issues/14
      - jsonify      # Public Domain https://github.com/substack/jsonify/blob/master/package.json#L29
      - map-stream   # MIT https://github.com/dominictarr/map-stream/blob/master/LICENCE
      - retire       # Apache-2.0 https://github.com/RetireJS/retire.js/blob/master/LICENSE.md
      - semver-utils # Apache-2.0 https://git.daplie.com/coolaj86/semver-utils/blob/master/package.json#L20
      - base64-js    # MIT https://github.com/beatgammit/base64-js/blob/master/LICENSE
