vile:
  ignore:
    - appveyor.yml
    - bower_components
    - coverage
    - LICENSE
    - coffeelint.json
    - .ackrc
    - .babelrc
    - .build
    - .npmignore
    - .travis.yml
    - .vim.custom
    - doc
    - .docs
    - node_modules
    - .nyc_output
    - tags
    - .test/fixtures/**
    - test/fixtures/**
    - .ctags
    - .git
    - circle.yml
    - .editorconfig
    - .eslintrc
    - .gitignore
    - .npmrc
    - npm-debug.log
    - src/@types
    - tags
    - tmp
    - tsconfig.json
    - retire-report.json
    - tslint.json
    - tsd.json
    - vendor
    - README.md
    - .vile.yml
    - yarn.lock

depcheck:
  config:
    ignore_dev_deps: true
    ignore_deps:
      - "@types/**"
    ignore_dirs:
      - src
      - .docs
      - node_modules
      - coverage
      - tmp

retire:
  ignore:
    - .docs/**

eclint:
  ignore:
    - lib
    - .test

escomplex:
  config:
    use_maintainability_index: false

language:
  ignore:
    - lib
    - .test

length:
  config:
    file: 120
    line: 80
  ignore:
    - lib
    - test
    - .test

stat:
  allow:
    - src
    - test
  ignore:
    - src/@types/**

eslint:
  allow:
    - src/*
  ignore:
    - lib
    - .test

coverage:
  config:
    path: coverage/lcov.info
