vile:
  ignore:
    - appveyor.yml
    - bower_components
    - coverage
    - LICENSE
    - coffeelint.json
    - .ackrc
    - .babelrc
    - .build
    - .npmignore
    - .travis.yml
    - doc
    - .docs
    - node_modules
    - .nyc_output
    - tags
    - .test/fixtures/**
    - test/fixtures/**
    - .ctags
    - .git
    - circle.yml
    - .editorconfig
    - .eslintrc
    - .gitignore
    - .npmrc
    - npm-debug.log
    - src/@types
    - tags
    - tmp
    - tsconfig.json
    - retire-report.json
    - tslint.json
    - tsd.json
    - vendor
    - README.md
    - .vile.yml
    - yarn.lock

depcheck:
  config:
    ignore_dev_deps: true
    ignore_deps:
      - "@types/**"
      - "vile-**"
    ignore_dirs:
      - src
      - .docs
      - node_modules
      - coverage
      - tmp

retire:
  ignore:
    - .docs/**

eclint:
  ignore:
    - lib
    - .test

escomplex:
  config:
    use_maintainability_index: false

language:
  ignore:
    - lib
    - .test

stat:
  allow:
    - src
    - test
  ignore:
    - src/@types/**

eslint:
  allow:
    - src/*
  ignore:
    - lib
    - .test

coverage:
  config:
    path: coverage/lcov.info

license:
  config:
    allowed:
      - MIT
      - ISC
      - MPL-2.0
      - BSD
      - Apache
      - Unlicense
      - Artistic
      - WTFPL
      - Public Domain
      - CC-BY-3.0
    ignored:
      - classifier   # MIT https://github.com/harthur/classifier/blob/master/LICENSE
      - event-stream # MIT https://github.com/dominictarr/event-stream/blob/master/LICENCE
      - map-stream   # MIT https://github.com/dominictarr/map-stream/blob/master/LICENCE
      - retire       # Apache-2.0 https://github.com/RetireJS/retire.js/blob/master/LICENSE.md
